### PR TITLE
konsole colorscheme: gray all

### PR DESCRIPTION
**Pull request by FadeMind**
@varlesh
pure clean gray in konsole

screenshot_20160601_131332
screenshot_20160601_131408
screenshot_20160601_131420
screenshot_20160601_131435
screenshot_20160601_131508
screenshot_20160601_131518

### CODE REVIEW

**Comment by varlesh** [comment]
Fine!

**Comment by varlesh** [comment]
@FadeMind Maybe change opacity to 0.9? Because plasma theme have 10% opacity and many people use Yakuake
screenshot_20160601_142728

**Comment by FadeMind** [comment]
@varlesh  opacity should be adjusted individually by user (if he used). 
I used solid (no transparent) aurorae papirus theme and for me all is fine.

**Comment by varlesh** [comment]
i add two version ))

**Comment by FadeMind** [comment]
So, makefile update upcomming xD

**Pull request merged**
